version: 2

jobs:
  pep8:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          command: |
            sudo pip install tox
            tox -e pep8
  py27:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run:
          command: |
            sudo pip install tox
            tox -e py27
  py35:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run:
          command: |
            sudo pip install tox
            tox -e py35
  py36:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          command: |
            sudo pip install tox
            tox -e py36
  py37:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: |
            sudo pip install tox
            tox -e py37
  py38:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          command: |
            sudo pip install tox
            tox -e py38
  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: |
          pip install twine
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = __token__ >> ~/.pypirc
            echo -e "password = $PYPI_TOKEN" >> ~/.pypirc
      - run:
          name: create packages
          command: |
            python setup.py sdist bdist_wheel
      - run:
          name: upload to PyPI
          command: |
            twine upload dist/*

workflows:
  version: 2

  test:
    jobs:
      - pep8
      - py27
      - py35
      - py36
      - py37
      - py38
      - deploy:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
